
data = [ 
    {"colKeyValue":1,  "colTitle":"Monument Valley",                                                "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"Slide",           "mineYN":false, "followingYN":false, "colStar":4},  
    {"colKeyValue":2,  "colTitle":"Niagara Falls",                                                  "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"Slide",           "mineYN":false, "followingYN":false, "colStar":5}, 
    {"colKeyValue":3,  "colTitle":"Interaken OST",                                                  "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"Slide",           "mineYN":false, "followingYN":false, "colStar":3}, 
    {"colKeyValue":4,  "colTitle":"Bryce Canyon National Park, USA",                                "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"Today's Journey", "mineYN":false, "followingYN":false, "colStar":5}, 
    {"colKeyValue":5,  "colTitle":"Seoul, Feel the Rhythm of Korea",                                "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"Sportlight",      "mineYN":true,  "followingYN":false, "colStar":4}, 
    {"colKeyValue":6,  "colTitle":"25 Beautiful Destinations in Europe",                            "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"Sportlight",      "mineYN":false, "followingYN":false, "colStar":3}, 
    {"colKeyValue":7,  "colTitle":"",                                                               "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":8,  "colTitle":"",                                                               "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":9,  "colTitle":"",                                                               "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":10, "colTitle":"",                                                               "colSection":"home",             "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":11, "colTitle":"The Top Gun Filming Location in San Diego",                      "colSection":"Theme Travel",     "colSubSection":"The places in Movies & TV",    "colSpecialSection":"Popular",         "mineYN":false, "followingYN":false, "colStar":5}, 
    {"colKeyValue":12, "colTitle":"Bumblebee at the Golden gate bridge",                            "colSection":"Theme Travel",     "colSubSection":"The places in Movies & TV",    "colSpecialSection":"",                "mineYN":false, "followingYN":true,  "colStar":4}, 
    {"colKeyValue":13, "colTitle":"KOREAN STREET FOOD",                                             "colSection":"Theme Travel",     "colSubSection":"Travel with a Food",           "colSpecialSection":"",                "mineYN":true,  "followingYN":false, "colStar":5}, 
    {"colKeyValue":14, "colTitle":"Traveling with Kids - Best Locations, Tips",                     "colSection":"Theme Travel",     "colSubSection":"Travel with children",         "colSpecialSection":"",                "mineYN":false, "followingYN":false, "colStar":5}, 
    {"colKeyValue":15, "colTitle":"BEST Family Holiday Destinations 2020",                          "colSection":"Theme Travel",     "colSubSection":"Travel with children",         "colSpecialSection":"",                "mineYN":false, "followingYN":true,  "colStar":4}, 
    {"colKeyValue":16, "colTitle":"Travel With Kids Rome",                                          "colSection":"Theme Travel",     "colSubSection":"Travel with children",         "colSpecialSection":"",                "mineYN":false, "followingYN":false, "colStar":5}, 
    {"colKeyValue":17, "colTitle":"PARIS WITH KIDS",                                                "colSection":"Theme Travel",     "colSubSection":"Travel with children",         "colSpecialSection":"",                "mineYN":false, "followingYN":false, "colStar":5}, 
    {"colKeyValue":18, "colTitle":"",                                                               "colSection":"Theme Travel",     "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":19, "colTitle":"",                                                               "colSection":"Theme Travel",     "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":20, "colTitle":"",                                                               "colSection":"Theme Travel",     "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":21, "colTitle":"Mother & Daughter Travel",                                       "colSection":"Memorable Places", "colSubSection":"Mother and daughter",          "colSpecialSection":"Popular",         "mineYN":false, "followingYN":false, "colStar":5}, 
    {"colKeyValue":22, "colTitle":"Universal Studio Graduation Trip",                               "colSection":"Memorable Places", "colSubSection":"Graduation trip",              "colSpecialSection":"",                "mineYN":false, "followingYN":true,  "colStar":4}, 
    {"colKeyValue":23, "colTitle":"Time travel to the past - Same place, same man, same gesture",   "colSection":"Memorable Places", "colSubSection":"Same place, different time",   "colSpecialSection":"",                "mineYN":false, "followingYN":false, "colStar":5}, 
    {"colKeyValue":24, "colTitle":"Same place different seasnons",                                  "colSection":"Memorable Places", "colSubSection":"Same place, different time",   "colSpecialSection":"",                "mineYN":false, "followingYN":false, "colStar":3}, 
    {"colKeyValue":25, "colTitle":"Grand Canyon Graduation Trip",                                   "colSection":"Memorable Places", "colSubSection":"Graduation trip",              "colSpecialSection":"Popular",         "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":26, "colTitle":"",                                                               "colSection":"Memorable Places", "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":27, "colTitle":"",                                                               "colSection":"Memorable Places", "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":28, "colTitle":"",                                                               "colSection":"Memorable Places", "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":29, "colTitle":"",                                                               "colSection":"Memorable Places", "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":30, "colTitle":"",                                                               "colSection":"Memorable Places", "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":31, "colTitle":"Top 5 | Hikes in the US and Canada",                             "colSection":"Travel Routes",    "colSubSection":"Hiking routes",                "colSpecialSection":"",                "mineYN":true, "followingYN":false, "colStar":4}, 
    {"colKeyValue":32, "colTitle":"Exploring Killarney! - Hiking The Crack",                        "colSection":"Travel Routes",    "colSubSection":"Hiking routes",                "colSpecialSection":"Popular",         "mineYN":true, "followingYN":false, "colStar":5}, 
    {"colKeyValue":33, "colTitle":"RV Trip Wizard - (BEST RV ROUTE PLANNER) - Full Time RV",        "colSection":"Travel Routes",    "colSubSection":"Driving routes",               "colSpecialSection":"",                "mineYN":true, "followingYN":true,  "colStar":4}, 
    {"colKeyValue":34, "colTitle":"The Arctic Coast Cycling Tour - FULL MOVIE",                     "colSection":"Travel Routes",    "colSubSection":"Bicycle routes",               "colSpecialSection":"",                "mineYN":true, "followingYN":false, "colStar":5}, 
    {"colKeyValue":35, "colTitle":"Cycling in Singapore: A 73km Scenery Route",                     "colSection":"Travel Routes",    "colSubSection":"Bicycle routes",               "colSpecialSection":"",                "mineYN":true, "followingYN":false, "colStar":3}, 
    {"colKeyValue":36, "colTitle":"",                                                               "colSection":"Travel Routes",    "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":37, "colTitle":"",                                                               "colSection":"Travel Routes",    "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":38, "colTitle":"",                                                               "colSection":"Travel Routes",    "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":39, "colTitle":"",                                                               "colSection":"Travel Routes",    "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""}, 
    {"colKeyValue":40, "colTitle":"",                                                               "colSection":"Travel Routes",    "colSubSection":"",                             "colSpecialSection":"",                "mineYN":"",    "followingYN":"",    "colStar":""} 
];


description = [
    {"colKeyValue":1,  "colDescription":"Monument Valley (Navajo], meaning valley of the rocks) is a region of the Colorado Plateau characterized by a cluster of vast sandstone buttes, the largest reaching 1,000 ft (300 m) above the valley floor. It is located on the Arizona–Utah state line (around 36°59′N 110°6′WCoordinates: 36°59′N 110°6′W), near the Four Corners area. The valley lies within the territory of the Navajo Nation Reservation and is accessible from U.S. Highway 163. Monument Valley has been featured in many forms of media since the 1930s. Director John Ford used the location for a number of his best-known films and thus, in the words of critic Keith Phipps, its five square miles [13 square kilometers] have defined what decades of moviegoers think of when they imagine the American West (Monument Valley, 2020)."},
    {"colKeyValue":2,  "colDescription":"Niagara Falls /naɪˈæɡrə, naɪˈæɡərə/ is a group of three waterfalls at the southern end of Niagara Gorge, spanning the border between the province of Ontario in Canada and the state of New York in the United States. The largest of the three is Horseshoe Falls, also known as Canadian Falls, which straddles the international border of the two countries. The smaller American Falls and Bridal Veil Falls lie within the United States. Bridal Veil Falls are separated from Horseshoe Falls by Goat Island and from American Falls by Luna Island, with both islands situated in New York (Niagara Falls, 2019)."}, 
    {"colKeyValue":3,  "colDescription":"Interlaken Ost or Interlaken East is a railway station in the resort town of Interlaken in the Swiss canton of Bern. The station was previously known as Interlaken Zollhaus. The town has one other station, Interlaken West. Interlaken Ost is an important railway junction at the meeting point of three railway lines, the Thunersee line of the BLS AG, the Brünig line of the Zentralbahn, and the Bernese Oberland railway (BOB). In addition to trains operated directly by the owners of these lines, the station is also reached by passenger trains of the Swiss Federal Railways, Deutsche Bahn, all of which operate over the Thunersee line (Interaken OST, 2020)."}, 
    {"colKeyValue":4,  "colDescription":"Bryce Canyon National Park, a sprawling reserve in southern Utah, is known for crimson-colored hoodoos, which are spire-shaped rock formations. The park’s main road leads past the expansive Bryce Amphitheater, a hoodoo-filled depression lying below the Rim Trail hiking path. It has overlooks at Sunrise Point, Sunset Point, Inspiration Point and Bryce Point. Prime viewing times are around sunup and sundown(Bryce Canyon, 2020)."}, 
    {"colKeyValue":5,  "colDescription":"Inalchi -- Beom Naeryeo'onda [Korean Folk/Fusion] (Imagine your Korea, 2020)"}, 
    {"colKeyValue":6,  "colDescription":"Europe is full of diverse and dreamy landscapes that belie its relatively small size(Touropia, 2020)."}, 
    {"colKeyValue":7,  "colDescription":""}, 
    {"colKeyValue":8,  "colDescription":""}, 
    {"colKeyValue":9,  "colDescription":""}, 
    {"colKeyValue":10, "colDescription":""}, 
    {"colKeyValue":11, "colDescription":"Kansas City Barbeque is a restaurant and bar located in the harbor district of San Diego, California. Self-proclaimed as the 'Top Gun Bar', it is known for being the filming location for scenes used in the film Top Gun.(Kensas City Barbeque, 2019)"}, 
    {"colKeyValue":12, "colDescription":"The filming Bumblebee (2018)'s view point is right here. Golden Gate Bridge! (Sceen It, 2018)"}, 
    {"colKeyValue":13, "colDescription":"Korean Street Food | Street Food in Seoul | Gwangjang Market. So PUMPED to be in Seoul, South Korea for a MASSIVE Street Food tour! We spent 7 days (Martin, 2017)."}, 
    {"colKeyValue":14, "colDescription":"Should we take our kids with us when we travel? Of course you should travel with them! (Wolters World, 2019)"}, 
    {"colKeyValue":15, "colDescription":"What are the BEST family holiday destinations in 2020? Here are our top picks (The Backpacking Family, 2018)."}, 
    {"colKeyValue":16, "colDescription":"Things to do with kids in Rome. Visiting Rome Italy with kids, visit the historical sites (Travel With Kids TV, 2012)."}, 
    {"colKeyValue":17, "colDescription":"Hi I'm Jess, single mum to two boys and a french bulldog named Peanut (Avey, 2018)."}, 
    {"colKeyValue":18, "colDescription":""}, 
    {"colKeyValue":19, "colDescription":""}, 
    {"colKeyValue":20, "colDescription":""}, 
    {"colKeyValue":21, "colDescription":"Carmen and Angelica share their experience as mother and daughter on pilgrimage in France to connect with the sacred feminine (Hirlaender, 2016)."}, 
    {"colKeyValue":22, "colDescription":"There is an amazing graduation trip to Universal studio, Hollywood! Universal Studios Hollywood is a film studio and theme park in the San Fernando Valley area of Los Angeles County, California. About 70% of the studio lies within the unincorporated county island known as Universal City while the rest lies within the city limits of Los Angeles, California. It is one of the oldest and most famous Hollywood film studios still in use. Its official marketing headline is 'The Entertainment Capital of LA'. It was initially created to offer tours of the real Universal Studios sets and is the first of many full-fledged Universal Studios Theme Parks located across the world (Universal Studios Hollywood, 2020)."}, 
    {"colKeyValue":23, "colDescription":"We've made this remake of an old random video at the same place. Just for fun! (Team WITW, 2018)"}, 
    {"colKeyValue":24, "colDescription":"#southlodge  #exclusivehotels #horsham #hotel #fivestar  #england #countryside #unitedkingdom (Henderson, 2020)"}, 
    {"colKeyValue":25, "colDescription":"The Grand Canyon (Hopi: Ongtupqa, Yavapai: Wi:kaʼi:la, Navajo: Bidááʼ Haʼaztʼiʼ Tsékooh, Spanish: Gran Cañón) is a steep-sided canyon carved by the Colorado River in Arizona, United States. The Grand Canyon is 277 miles (446 km) long, up to 18 miles (29 km) wide and attains a depth of over a mile (6,093 feet or 1,857 meters). The canyon and adjacent rim are contained within Grand Canyon National Park, the Kaibab National Forest, Grand Canyon–Parashant National Monument, the Hualapai Indian Reservation, the Havasupai Indian Reservation and the Navajo Nation. President Theodore Roosevelt was a major proponent of preservation of the Grand Canyon area and visited it on numerous occasions to hunt and enjoy the scenery(Grand Canyon, 2020)."}, 
    {"colKeyValue":26, "colDescription":""}, 
    {"colKeyValue":27, "colDescription":""}, 
    {"colKeyValue":28, "colDescription":""}, 
    {"colKeyValue":29, "colDescription":""}, 
    {"colKeyValue":30, "colDescription":""}, 
    {"colKeyValue":31, "colDescription":"Hey there friends! This video takes you through our favorite hikes in North America thus far! We'd love to hear what are some of your favorite hikes out there! (Bound For Nowhere, 2019)"}, 
    {"colKeyValue":32, "colDescription":"This place has been on my list for a very long time and finally made a trip up to this park to experience it for myself. This place is filled with epics scenery and landscapes. and during fall it's a photographers dream! (Sedran, 2017)"}, 
    {"colKeyValue":33, "colDescription":"RV Trip Wizard - RV Route Planner - Full Time RV: RV Trip Wizard makes Rv Trip planning easy. I love using the RV Trip Wizard app because it makes my RV route planning easy. If you are looking for an RV route planner, RV Trip Wizard is the perfect one to choose(You Me & the RV, 2019)."}, 
    {"colKeyValue":34, "colDescription":"Follow along as Darren Alff and Sophie Wilkie participate in the \"Arctic Coast Cycling Tour\" with Active-Norway.com(Bicycle Touring Pro, 2017)."}, 
    {"colKeyValue":35, "colDescription":"This is a 73km route mostly utilising Park Connect (PCN), starting from Bishan Park and cycling through the most scenery parts of Singapore south, east and north rivers and coast line, creating a 73km coast-to-coast circle route. The original route info is available at (Cheung, 2017)."}, 
    {"colKeyValue":36, "colDescription":""}, 
    {"colKeyValue":37, "colDescription":""}, 
    {"colKeyValue":38, "colDescription":""}, 
    {"colKeyValue":39, "colDescription":""}, 
    {"colKeyValue":40, "colDescription":""} 
];

contentsMedia = [
    {"colKeyValue":1,  "colMediaType":"IMG",    "colMediaUrl":"images/slideimg1.jpg"},
    {"colKeyValue":2,  "colMediaType":"IMG",    "colMediaUrl":"images/slideimg2.jpg"},
    {"colKeyValue":3,  "colMediaType":"IMG",    "colMediaUrl":"images/slideimg3.jpg"},
    {"colKeyValue":4,  "colMediaType":"IMG",    "colMediaUrl":"images/brycecanyon.jpg"},
    {"colKeyValue":5,  "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/3P1CnWI62Ik"},
    {"colKeyValue":6,  "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/7lvXbfNBIQg"},
    {"colKeyValue":7,  "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":8,  "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":9,  "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":10, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":11, "colMediaType":"IMG",    "colMediaUrl":"images/topgun.jpg"},
    {"colKeyValue":12, "colMediaType":"IMG",    "colMediaUrl":"images/goldengatebridge.jpg"},
    {"colKeyValue":13, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/cVZheE7mNR4"},
    {"colKeyValue":14, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/f7aCwu_SjMo"},
    {"colKeyValue":15, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/yC2BYCPB40w"},
    {"colKeyValue":16, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/iXo1ApC2R9E"},
    {"colKeyValue":17, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/9WfA5BSnxj8"},
    {"colKeyValue":18, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":19, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":20, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":21, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/knvxFkvEE1M"},
    {"colKeyValue":22, "colMediaType":"IMG",    "colMediaUrl":"images/universalstudio.jpg"},
    {"colKeyValue":23, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/9rEFg7-NYgk"},
    {"colKeyValue":24, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/JGfLKtOkplU"},
    {"colKeyValue":25, "colMediaType":"IMG",    "colMediaUrl":"images/grandcanyon.jpg"},
    {"colKeyValue":26, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":27, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":28, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":29, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":30, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":31, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/dr2j5U427FE"},
    {"colKeyValue":32, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/HhILvf0xqFM"},
    {"colKeyValue":33, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/03lUrlF0K3k"},
    {"colKeyValue":34, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/yvR8P3G9mqE"},
    {"colKeyValue":35, "colMediaType":"IFRAME", "colMediaUrl":"https://www.youtube.com/embed/eatQigHCmrY"},
    {"colKeyValue":36, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":37, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":38, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":39, "colMediaType":"IFRAME", "colMediaUrl":""},
    {"colKeyValue":40, "colMediaType":"IFRAME", "colMediaUrl":""} 
];


locationMap = [
    {"colKeyValue":1,  "colMap":"37.304839135074715, -110.03073640907957"},
    {"colKeyValue":2,  "colMap":"43.08335851369308, -79.0742405472104"}, 
    {"colKeyValue":3,  "colMap":"46.69056384692816, 7.869008082756555"}, 
    {"colKeyValue":4,  "colMap":"37.60757439411429, -112.18587471902397"}, 
    {"colKeyValue":5,  "colMap":"37.57616646288585, 126.97685861321467"}, 
    {"colKeyValue":6,  "colMap":"48.96809950924573, 16.47184992172501"}, 
    {"colKeyValue":7,  "colMap":""}, 
    {"colKeyValue":8,  "colMap":""}, 
    {"colKeyValue":9,  "colMap":""}, 
    {"colKeyValue":10, "colMap":""}, 
    {"colKeyValue":11, "colMap":"32.711795644069525, -117.16869328843669"}, 
    {"colKeyValue":12, "colMap":"37.82148241933201, -122.4781812170255"}, 
    {"colKeyValue":13, "colMap":"37.57033125833205, 126.99936185554394"}, 
    {"colKeyValue":14, "colMap":""}, 
    {"colKeyValue":15, "colMap":""}, 
    {"colKeyValue":16, "colMap":"41.8977204343405, 12.505777874862266"}, 
    {"colKeyValue":17, "colMap":"48.85477167455924, 2.3326386250539546"}, 
    {"colKeyValue":18, "colMap":""}, 
    {"colKeyValue":19, "colMap":""}, 
    {"colKeyValue":20, "colMap":""}, 
    {"colKeyValue":21, "colMap":"46.77732293630743, 2.616687192795062"}, 
    {"colKeyValue":22, "colMap":"34.13819743406804, -118.35330543362792"}, 
    {"colKeyValue":23, "colMap":""}, 
    {"colKeyValue":24, "colMap":"51.01612026495833, -0.2639663252855105"}, 
    {"colKeyValue":25, "colMap":"36.10672547299728, -112.11637283224071"}, 
    {"colKeyValue":26, "colMap":""}, 
    {"colKeyValue":27, "colMap":""}, 
    {"colKeyValue":28, "colMap":""}, 
    {"colKeyValue":29, "colMap":""}, 
    {"colKeyValue":30, "colMap":""}, 
    {"colKeyValue":31, "colMap":"40.47101234534532, -96.80558199091608"}, 
    {"colKeyValue":32, "colMap":"46.013083502552696, -81.40173718890524"}, 
    {"colKeyValue":33, "colMap":"39.605331881710434, -102.793807206824"}, 
    {"colKeyValue":34, "colMap":"70.94629171130859, 27.34715448117541"}, 
    {"colKeyValue":35, "colMap":"1.3628329467549554, 103.84249449573811"}, 
    {"colKeyValue":36, "colMap":""}, 
    {"colKeyValue":37, "colMap":""}, 
    {"colKeyValue":38, "colMap":""}, 
    {"colKeyValue":39, "colMap":""}, 
    {"colKeyValue":40, "colMap":""} 
];

userComments = [
    {"colKeyValue":1,  "colComment":"Cool~, #western era #dust #forest gump, I'd like to go there., I've been there with my family two year ago., Sounds Good, It's so sad to be at home these days because of COVID-19."},
    {"colKeyValue":2,  "colComment":"#huge scale, #rainbow, #boat tour"}, 
    {"colKeyValue":3,  "colComment":"Switzerland, Perpetual snows, Glacial water with melting ice caps, Let's get on the cog train to visit the peak of Jungfrau!"}, 
    {"colKeyValue":4,  "colComment":"#Trail course, #Hiking, #Awsome Scenery"}, 
    {"colKeyValue":5,  "colComment":"#Amazing tune, #Want to visit, #Memorable, #Great work by the advertising team"}, 
    {"colKeyValue":6,  "colComment":"#Beautiful Places, Wonderful creation"}, 
    {"colKeyValue":7,  "colComment":""}, 
    {"colKeyValue":8,  "colComment":""}, 
    {"colKeyValue":9,  "colComment":""}, 
    {"colKeyValue":10, "colComment":""}, 
    {"colKeyValue":11, "colComment":"The location director for Paramount Studios visited Kansas City Barbeque for a beer while working in San Diego., Right!!! He liked the atmosphere and brought the bar to the attention of film director Tony Scott., Scott asked the owners to shut the establishment down for a day in order use the bar for shooting., The bar was used in a scene in which Goose and Maverick (played by Anthony Edwards and Tom Cruise, respectively) belt out 'Great Balls of Fire' while seated at the piano., The now famous line by Meg Ryan' Goose, you big stuuuuuud! Take me to bed or lose me forever!' was uttered in the dining area of Kansas City Barbeque., The bar was also used in the final scene, where the song 'You've Lost That Lovin' Feelin'' is heard playing on the jukebox., Wikipedia 2019"}, 
    {"colKeyValue":12, "colComment":"An actor : Hailee Steinfeld(Charlie Watson)!!!, #San francisco, #Bumblebee, #RODEO BEACH"}, 
    {"colKeyValue":13, "colComment":"#Yummy Yummy Ymmmy, #Traditional market, #Korean Food"}, 
    {"colKeyValue":14, "colComment":""}, 
    {"colKeyValue":15, "colComment":"#Beach, #Adventure, #Resort, #Thailand, #Prague, #England, #Bali"}, 
    {"colKeyValue":16, "colComment":"#Rome, #Italy, #Gladiator, #Colosseum"}, 
    {"colKeyValue":17, "colComment":""}, 
    {"colKeyValue":18, "colComment":""}, 
    {"colKeyValue":19, "colComment":""}, 
    {"colKeyValue":20, "colComment":""}, 
    {"colKeyValue":21, "colComment":"#Experience,#Pilgrimage, #France"}, 
    {"colKeyValue":22, "colComment":"#Graduation Trip, #Theme park, #Hollywood"}, 
    {"colKeyValue":23, "colComment":"#Just Fun!!!"}, 
    {"colKeyValue":24, "colComment":""}, 
    {"colKeyValue":25, "colComment":"#Colorado River, #South Rim, #Channels"}, 
    {"colKeyValue":26, "colComment":""}, 
    {"colKeyValue":27, "colComment":""}, 
    {"colKeyValue":28, "colComment":""}, 
    {"colKeyValue":29, "colComment":""}, 
    {"colKeyValue":30, "colComment":""}, 
    {"colKeyValue":31, "colComment":"#North America, #Hikes, #National Parks"}, 
    {"colKeyValue":32, "colComment":"#Canada, #Ontario, #Excellent trail route, #Hiking"}, 
    {"colKeyValue":33, "colComment":"#RV Trip #RV Vehicles #Parks, #Route Planning, #Camp ground"}, 
    {"colKeyValue":34, "colComment":"#Bicycle #Adventure #Norway, #Arctic Coast, #Fabulous video #Wonderful photography"}, 
    {"colKeyValue":35, "colComment":""}, 
    {"colKeyValue":36, "colComment":""}, 
    {"colKeyValue":37, "colComment":""}, 
    {"colKeyValue":38, "colComment":""}, 
    {"colKeyValue":39, "colComment":""}, 
    {"colKeyValue":40, "colComment":""} 
];

relatedUrls = [
    {"colKeyValue":1,  "colRelatedSite":"Wikipedia 2020 - Monument Valley, Booking Tours, Navajo Nation Parks", "colRelatedUrl":"https://en.wikipedia.org/wiki/Monument_Valley, https://www.monument-valley.com/, https://navajonationparks.org/tribal-parks/monument-valley/"},
    {"colKeyValue":2,  "colRelatedSite":"Wikipedia 2020 - Niagara Falls", "colRelatedUrl":"https://en.wikipedia.org/wiki/Niagara_Falls"}, 
    {"colKeyValue":3,  "colRelatedSite":"Wikipedia 2020 - Interaken OST", "colRelatedUrl":"https://en.wikipedia.org/wiki/Interlaken_Ost_railway_station"}, 
    {"colKeyValue":4,  "colRelatedSite":"Wikipedia 2020 - Bryce Canyon", "colRelatedUrl":"https://en.wikipedia.org/wiki/Bryce_Canyon_National_Park"}, 
    {"colKeyValue":5,  "colRelatedSite":"Imagine your Korea 2020 - Feel the Rhythm of Korea: SEOUL", "colRelatedUrl":"https://www.youtube.com/watch?v=3P1CnWI62Ik&feature=youtu.be"}, 
    {"colKeyValue":6,  "colRelatedSite":"Touropia 2020 - 25 Most Beautiful Destination in Europe", "colRelatedUrl":"https://www.youtube.com/watch?v=7lvXbfNBIQg&feature=youtu.be"}, 
    {"colKeyValue":7,  "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":8,  "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":9,  "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":10, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":11, "colRelatedSite":"Wikipedia 2019 - Kensas City Barbeque", "colRelatedUrl":"https://en.wikipedia.org/wiki/Kansas_City_Barbeque"}, 
    {"colKeyValue":12, "colRelatedSite":"Sceen It 2018 - Golden gate bridge view point: Bumblebee 2018", "colRelatedUrl":"https://www.sceen-it.com/sceen/2554/Bumblebee/Golden-Gate-Bridge-View-Point"}, 
    {"colKeyValue":13, "colRelatedSite":"Luke Martin 2017 - Korean Street Food", "colRelatedUrl":"https://www.youtube.com/watch?v=cVZheE7mNR4&feature=youtu.be"}, 
    {"colKeyValue":14, "colRelatedSite":"Wolters World 2019 - Traveling with Kids - Best Locations", "colRelatedUrl":"https://www.youtube.com/watch?v=f7aCwu_SjMo&feature=youtu.be"}, 
    {"colKeyValue":15, "colRelatedSite":"The Backpacking Family 2018 - BEST Family Holiday Destinations 2020", "colRelatedUrl":"https://www.youtube.com/watch?v=yC2BYCPB40w&feature=youtu.be"}, 
    {"colKeyValue":16, "colRelatedSite":"Travel With Kids TV 2012 - Rome with Kids - Travel With Kids Rome", "colRelatedUrl":"https://www.youtube.com/watch?v=iXo1ApC2R9E&feature=youtu.be"}, 
    {"colKeyValue":17, "colRelatedSite":"Jessica Avey 2018 - Paris with kids", "colRelatedUrl":"https://www.youtube.com/watch?v=9WfA5BSnxj8&feature=youtu.be"}, 
    {"colKeyValue":18, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":19, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":20, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":21, "colRelatedSite":"Nina Hirlaender 2016 - Mothers & Daughter Travel", "colRelatedUrl":"https://www.youtube.com/watch?v=knvxFkvEE1M&feature=youtu.be"}, 
    {"colKeyValue":22, "colRelatedSite":"Wikipedia 2020 - Universal Studios Hollywood", "colRelatedUrl":"https://en.wikipedia.org/wiki/Universal_Studios_Hollywood"},
    {"colKeyValue":23, "colRelatedSite":"Team WITW 2018 - Time travel to the past", "colRelatedUrl":"https://www.youtube.com/watch?v=9rEFg7-NYgk&feature=youtu.be"}, 
    {"colKeyValue":24, "colRelatedSite":"Merita Henderson 2020 - Same place different seasons", "colRelatedUrl":"https://www.youtube.com/watch?v=JGfLKtOkplU&feature=youtu.be"}, 
    {"colKeyValue":25, "colRelatedSite":"Wikipedia 2020 - Grand Canyon", "colRelatedUrl":"https://en.wikipedia.org/wiki/Grand_Canyon"},
    {"colKeyValue":26, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":27, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":28, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":29, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":30, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":31, "colRelatedSite":"Bound For Nowhere 2019 - Top 5 Hikes in the US and Canada", "colRelatedUrl":"https://www.youtube.com/watch?v=dr2j5U427FE&feature=youtu.be"}, 
    {"colKeyValue":32, "colRelatedSite":"Dan Sedran 2017 - Exploring Killarney! - Hiking 'The Crack'", "colRelatedUrl":"https://www.youtube.com/watch?v=HhILvf0xqFM&feature=youtu.be"}, 
    {"colKeyValue":33, "colRelatedSite":"You Me & the RV 2019", "colRelatedUrl":"https://www.youtube.com/watch?v=03lUrlF0K3k&feature=youtu.be"}, 
    {"colKeyValue":34, "colRelatedSite":"Bicycle Touring Pro 2017 - The Arctic Coast Cycling Tour", "colRelatedUrl":"https://www.youtube.com/watch?v=yvR8P3G9mqE&feature=youtu.be"}, 
    {"colKeyValue":35, "colRelatedSite":"Henry Cheung 2017 - Cycling in Singapore", "colRelatedUrl":"https://www.youtube.com/watch?v=eatQigHCmrY&feature=youtu.be"}, 
    {"colKeyValue":36, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":37, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":38, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":39, "colRelatedSite":"", "colRelatedUrl":""}, 
    {"colKeyValue":40, "colRelatedSite":"", "colRelatedUrl":""} 
];
